server {
  listen 80;

  # 프론트 배포본(dist) 제공
  location / {
    proxy_pass http://medinote-front:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # 백엔드 API
  location /api/ {
    proxy_pass http://medinote-back-kc:8083/api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
